name: SmallRye Build

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          { 'version': '11', 'opts': '-DskipTests' },
          { 'version': '17', 'opts': '-DskipTests' },
          { 'version': '20', 'opts': '-DskipTests' },
          { 'version': '21', 'opts': '-DskipTests'}
        ]
    name: build with jdk ${{matrix.java.version}}

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - uses: actions/setup-java@v4
        name: set up jdk ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: maven

      - name: build with maven
        run: mvn -B install --file pom.xml ${{matrix.java.opts}}